services:
  - type: web
    name: kango-pair-site
    env: docker
    plan: free
    branch: main
    repo: https://github.com/Viniznimco/QUEEN-BRESHY
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    
